spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://USER/
          predicates:
            - Path=/user/**
        - id: login
          uri: lb://USER/
          predicates:
            - Path=/login
server:
  port: 8079

eureka:
  instance:
    status-page-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5