spring:
  application:
    name: "gateway"
  cloud:
    client:
      hostname: http://raspberrytronxi2.ddns.net
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://USER/
          predicates:
            - Path=/user-service/**
        - id: subject
          uri: lb://SUBJECT/
          predicates:
            - Path=/subject-service/**
server:
  port: 8079

eureka:
  instance:
    status-page-url-path: ${spring.cloud.client.hostname}:${server.port}/actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://raspberrytronxi2.ddns.net:8762/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5