spring:
  application:
    name: "gateway"
  cloud:
#    client:
#      hostname: http://raspberrytronxi2.ddns.net
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://USER/
          predicates:
            - Path=/user-service/**
        - id: subject
          uri: lb://SUBJECT/
          predicates:
            - Path=/subject-service/**
server:
  port: 8079
eureka-host: http://raspberrytronxi2.ddns.net
eureka:
  instance:
    status-page-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka-host}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5